fixtures:
  repositories:
    archive:
      repo: "git://github.com/voxpupuli/puppet-archive"
      ref: "v4.4.0"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat"
      ref: "v6.2.0"
    cron:
      repo: "git://github.com/puppetlabs/puppetlabs-cron_core"
      ref: "1.0.3"
    logrotate:
      repo: "git://github.com/voxpupuli/puppet-logrotate"
      ref: "v4.0.0"
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "v6.2.0"
  symlinks:
    duplicity: "#{source_dir}"

