fixtures:
  repositories:
    archive:
      repo: "https://github.com/camptocamp/puppet-archive.git"
      ref: "0.7.4"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.1.0"
    logrotate:
      repo: "https://github.com/yo61/puppet-logrotate.git"
      ref: "v1.3.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.2.1"
  symlinks:
    duplicity: "#{source_dir}"

