fixtures:
  forge_modules:
    archive:
      repo: "camptocamp/archive"
      ref: "0.7.4"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.1.0"
    logrotate:
      repo: "rodjek/logrotate"
      ref: "1.1.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.2.1"
  symlinks:
    duplicity: "#{source_dir}"

