fixtures:
  repositories:
    archive:
      repo: "git://github.com/camptocamp/puppet-archive"
      ref: "0.9.0"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat"
      ref: "5.0.0"
    logrotate:
      repo: "git://github.com/voxpupuli/puppet-logrotate"
      ref: "v3.3.0"
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.25.1"
  symlinks:
    duplicity: "#{source_dir}"

